# 01 - Data Audit

## Objectif
Comprendre la structure du dataset Olist avant le nettoyage.

## Questions à traiter
- Quelles sont les tables disponibles ?
- Quelle est la granularité de chaque table ?
- Quelles colonnes contiennent des valeurs manquantes ?
- Quelles colonnes sont des dates ?
- Y a-t-il des doublons ?

In [129]:
from pathlib import Path
import pandas as pd

DATA_DIR = Path("../data/raw")
DATA_DIR

WindowsPath('../data/raw')

In [130]:
files = {
    "customers": "olist_customers_dataset.csv",
    "orders": "olist_orders_dataset.csv",
    "order_items": "olist_order_items_dataset.csv",
    "payments": "olist_order_payments_dataset.csv",
    "products": "olist_products_dataset.csv",
    "sellers": "olist_sellers_dataset.csv",
    "reviews": "olist_order_reviews_dataset.csv",
}

dfs = {}

for name, file_name in files.items():
    file_path = DATA_DIR / file_name
    dfs[name] = pd.read_csv(file_path)
    print(f"{name}: {dfs[name].shape}")

customers: (99441, 5)
orders: (99441, 8)
order_items: (112650, 7)
payments: (103886, 5)
products: (32951, 9)
sellers: (3095, 4)
reviews: (99224, 7)

In [131]:
def audit_table(df: pd.DataFrame, name: str) -> pd.DataFrame:
    summary = pd.DataFrame({
        "column": df.columns,
        "dtype": df.dtypes.astype(str).values,
        "missing_count": df.isna().sum().values,
        "missing_pct": (df.isna().mean() * 100).round(2).values,
        "n_unique": df.nunique(dropna=True).values
    })

    print(f"\n=== TABLE: {name} ===")
    print(f"shape: {df.shape}")
    print(f"duplicates: {df.duplicated().sum()}")
    display(df.head())
    display(summary)

    return summary

In [132]:
audit_results = {}

for name, df in dfs.items():
    audit_results[name] = audit_table(df, name)

=== TABLE: customers ===
shape: (99441, 5)
duplicates: 0

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

                     column  dtype  missing_count  missing_pct  n_unique
0               customer_id    str              0          0.0     99441
1        customer_unique_id    str              0          0.0     96096
2  customer_zip_code_prefix  int64              0          0.0     14994
3             customer_city    str              0          0.0      4119
4            customer_state    str              0          0.0        27

=== TABLE: orders ===
shape: (99441, 8)
duplicates: 0

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

                          column dtype  missing_count  missing_pct  n_unique
0                       order_id   str              0         0.00     99441
1                    customer_id   str              0         0.00     99441
2                   order_status   str              0         0.00         8
3       order_purchase_timestamp   str              0         0.00     98875
4              order_approved_at   str            160         0.16     90733
5   order_delivered_carrier_date   str           1783         1.79     81018
6  order_delivered_customer_date   str           2965         2.98     95664
7  order_estimated_delivery_date   str              0         0.00       459

=== TABLE: order_items ===
shape: (112650, 7)
duplicates: 0

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

                column    dtype  missing_count  missing_pct  n_unique
0             order_id      str              0          0.0     98666
1        order_item_id    int64              0          0.0        21
2           product_id      str              0          0.0     32951
3            seller_id      str              0          0.0      3095
4  shipping_limit_date      str              0          0.0     93318
5                price  float64              0          0.0      5968
6        freight_value  float64              0          0.0      6999

=== TABLE: payments ===
shape: (103886, 5)
duplicates: 0

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

                 column    dtype  missing_count  missing_pct  n_unique
0              order_id      str              0          0.0     99440
1    payment_sequential    int64              0          0.0        29
2          payment_type      str              0          0.0         5
3  payment_installments    int64              0          0.0        24
4         payment_value  float64              0          0.0     29077

=== TABLE: products ===
shape: (32951, 9)
duplicates: 0

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

                       column    dtype  missing_count  missing_pct  n_unique
0                  product_id      str              0         0.00     32951
1       product_category_name      str            610         1.85        73
2         product_name_lenght  float64            610         1.85        66
3  product_description_lenght  float64            610         1.85      2960
4          product_photos_qty  float64            610         1.85        19
5            product_weight_g  float64              2         0.01      2204
6           product_length_cm  float64              2         0.01        99
7           product_height_cm  float64              2         0.01       102
8            product_width_cm  float64              2         0.01        95

=== TABLE: sellers ===
shape: (3095, 4)
duplicates: 0

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

                   column  dtype  missing_count  missing_pct  n_unique
0               seller_id    str              0          0.0      3095
1  seller_zip_code_prefix  int64              0          0.0      2246
2             seller_city    str              0          0.0       611
3            seller_state    str              0          0.0        23

=== TABLE: reviews ===
shape: (99224, 7)
duplicates: 0

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

                    column  dtype  missing_count  missing_pct  n_unique
0                review_id    str              0         0.00     98410
1                 order_id    str              0         0.00     98673
2             review_score  int64              0         0.00         5
3     review_comment_title    str          87656        88.34      4527
4   review_comment_message    str          58247        58.70     36159
5     review_creation_date    str              0         0.00       636
6  review_answer_timestamp    str              0         0.00     98248

## Synthèse de l’audit

### Granularité
- `orders` : 1 ligne par commande
- `order_items` : 1 ligne par produit dans une commande
- `payments` : 1 ligne par paiement
- `products` : 1 ligne par produit
- `sellers` : 1 ligne par vendeur
- `reviews` : 1 ligne par avis, mais `order_id` n’est pas unique
- `customers` : 1 ligne par `customer_id`

### Colonnes date à convertir
- orders: `order_purchase_timestamp`, `order_approved_at`, `order_delivered_carrier_date`, `order_delivered_customer_date`, `order_estimated_delivery_date`
- order_items: `shipping_limit_date`
- reviews: `review_creation_date`, `review_answer_timestamp`

### Valeurs manquantes principales
- `orders`: plusieurs dates manquantes
- `products`: informations produit manquantes sur certaines lignes
- `reviews`: beaucoup de commentaires manquants

### Risques
- duplication des ventes lors des jointures
- confusion entre granularité commande et item
- mauvaise interprétation des valeurs manquantes

## Audit initial des données

Dans cette première étape, j’ai réalisé un audit initial du dataset e-commerce Olist afin de comprendre sa structure avant de commencer le nettoyage, l’analyse business et la modélisation.

J’ai d’abord chargé les principales tables du dataset dans des DataFrames Pandas à partir des fichiers CSV stockés dans le dossier `data/raw`. Cette étape m’a permis de vérifier que les données étaient bien accessibles et de mesurer la taille de chaque table à l’aide de leur dimension (`shape`), c’est-à-dire le nombre de lignes et de colonnes.

J’ai ensuite construit une fonction d’audit pour examiner chaque table de manière systématique. Pour chaque jeu de données, j’ai observé les colonnes disponibles, les types de variables, le nombre de valeurs manquantes, le nombre de valeurs uniques, les éventuels doublons ainsi qu’un aperçu des premières lignes.

Cette analyse a montré que le dataset est composé de plusieurs tables relationnelles avec des granularités différentes. La table `orders` semble être la table centrale car elle représente les commandes, tandis que `order_items` décrit les produits présents dans chaque commande et `payments` les paiements associés. Cette différence de granularité est essentielle, car une mauvaise jointure entre les tables pourrait entraîner une duplication artificielle des ventes.

L’audit a également permis d’identifier plusieurs colonnes de dates actuellement stockées sous forme de texte, qui devront être converties en format `datetime` pour permettre des analyses temporelles. Enfin, des valeurs manquantes ont été détectées dans certaines tables, notamment dans `orders`, `products` et `reviews`. Ces absences ne correspondent pas toutes à des erreurs de qualité : certaines peuvent s’expliquer par le contexte métier, par exemple l’absence de commentaire texte dans un avis client.

Cette étape d’audit constitue une base importante pour la suite du projet, car elle permet de préparer un nettoyage cohérent, de sécuriser les futures jointures SQL et Python, et d’éviter des erreurs d’interprétation dans l’analyse et la prédiction des ventes.

## 02 - Initial Cleaning and Date Conversion

In [133]:
date_columns = {
    "orders": [
        "order_purchase_timestamp",
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date",
        "order_estimated_delivery_date",
    ],
    "order_items": [
        "shipping_limit_date",
    ],
    "reviews": [
        "review_creation_date",
        "review_answer_timestamp",
    ],
}

In [134]:
for table_name, cols in date_columns.items():
    for col in cols:
        dfs[table_name][col] = pd.to_datetime(dfs[table_name][col], errors="coerce")

In [135]:
for table_name, cols in date_columns.items():
    print(f"\n=== {table_name} ===")
    print(dfs[table_name][cols].dtypes)

=== orders ===
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

=== order_items ===
shipping_limit_date    datetime64[us]
dtype: object

=== reviews ===
review_creation_date       datetime64[us]
review_answer_timestamp    datetime64[us]
dtype: object

In [136]:
dfs["orders"]["order_status"].value_counts(dropna=False)

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [137]:
print("orders.order_id unique:", dfs["orders"]["order_id"].is_unique)
print("customers.customer_id unique:", dfs["customers"]["customer_id"].is_unique)
print("products.product_id unique:", dfs["products"]["product_id"].is_unique)
print("sellers.seller_id unique:", dfs["sellers"]["seller_id"].is_unique)
print("reviews.review_id unique:", dfs["reviews"]["review_id"].is_unique)

orders.order_id unique: True
customers.customer_id unique: True
products.product_id unique: True
sellers.seller_id unique: True
reviews.review_id unique: False

In [138]:
orders_ids = set(dfs["orders"]["order_id"])
items_ids = set(dfs["order_items"]["order_id"])
payments_ids = set(dfs["payments"]["order_id"])
reviews_ids = set(dfs["reviews"]["order_id"])

print("Orders without items:", len(orders_ids - items_ids))
print("Orders without payments:", len(orders_ids - payments_ids))
print("Orders without reviews:", len(orders_ids - reviews_ids))

Orders without items: 775
Orders without payments: 1
Orders without reviews: 768

In [139]:
orders_clean = dfs["orders"].copy()
orders_clean.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26

In [140]:
orders_clean["purchase_year"] = orders_clean["order_purchase_timestamp"].dt.year
orders_clean["purchase_month"] = orders_clean["order_purchase_timestamp"].dt.month
orders_clean["purchase_day"] = orders_clean["order_purchase_timestamp"].dt.day
orders_clean["purchase_hour"] = orders_clean["order_purchase_timestamp"].dt.hour
orders_clean["purchase_dayofweek"] = orders_clean["order_purchase_timestamp"].dt.dayofweek

orders_clean[
    [
        "order_purchase_timestamp",
        "purchase_year",
        "purchase_month",
        "purchase_day",
        "purchase_hour",
        "purchase_dayofweek",
    ]
].head()

,order_purchase_timestamp,purchase_year,purchase_month,purchase_day,purchase_hour,purchase_dayofweek
0,2017-10-02 10:56:33,2017,10,2,10,0
1,2018-07-24 20:41:37,2018,7,24,20,1
2,2018-08-08 08:38:49,2018,8,8,8,2
3,2017-11-18 19:28:06,2017,11,18,19,5
4,2018-02-13 21:18:39,2018,2,13,21,1

## Etape 02 - Nettoyage initial et conversion des données

Dans cette deuxième étape, l’objectif était de préparer les données pour les futures analyses business et pour la construction d’une table analytique exploitable. Après avoir identifié la structure générale du dataset lors de l’audit initial, il était nécessaire de réaliser un premier nettoyage technique sur les tables principales.

La première action a consisté à repérer les colonnes contenant des informations temporelles dans les tables `orders`, `order_items` et `reviews`. Lors du chargement initial, ces colonnes étaient interprétées comme des chaînes de caractères. Elles ont donc été converties au format `datetime` avec la fonction `pd.to_datetime()`. Le paramètre `errors="coerce"` a été utilisé afin de transformer les éventuelles valeurs invalides en valeurs manquantes temporelles (`NaT`) plutôt que de provoquer une erreur bloquante. Cette étape est essentielle pour permettre des analyses temporelles fiables, comme l’étude des ventes par mois, par jour ou par heure.

Ensuite, une analyse de la variable `order_status` a été réalisée afin de mieux comprendre le cycle de vie des commandes. Cette vérification a montré que la grande majorité des commandes sont au statut `delivered`, tandis qu’une partie plus faible correspond à des commandes annulées, indisponibles, en cours de traitement ou simplement créées. Cette observation est importante car toutes les commandes ne représentent pas nécessairement une vente finalisée. Il faudra donc tenir compte de ce statut lors des futures analyses.

Une vérification des identifiants principaux a également été effectuée. Les colonnes `order_id`, `customer_id`, `product_id` et `seller_id` se sont révélées uniques dans leurs tables respectives, ce qui confirme leur rôle d’identifiants fiables pour les jointures. En revanche, `review_id` n’est pas unique dans la table `reviews`, ce qui indique qu’il faudra manipuler cette table avec précaution.

L’étape suivante a consisté à comparer les identifiants de commandes présents dans plusieurs tables afin de détecter d’éventuels écarts. Cette vérification a montré que certaines commandes n’ont pas de ligne correspondante dans `order_items`, qu’une commande ne possède pas de paiement enregistré, et qu’un certain nombre de commandes n’ont pas d’avis associé. Ces résultats montrent que toutes les commandes ne sont pas systématiquement représentées dans toutes les tables, ce qui devra être pris en compte lors de la construction de la table analytique.

Enfin, une copie de travail de la table `orders` a été créée sous le nom `orders_clean`. Cette copie permet de transformer les données sans modifier directement la table brute d’origine. Des variables temporelles dérivées ont ensuite été ajoutées, comme l’année, le mois, le jour, l’heure d’achat et le jour de la semaine. Ces nouvelles variables seront utiles à la fois pour l’analyse exploratoire et pour de futurs modèles de machine learning.

Cette étape de nettoyage initial a donc permis de sécuriser les données, de préparer les futures jointures et de poser les bases d’une analyse temporelle des ventes.

## 03 - Build the Analytical Sales Table

In [141]:
order_items_agg = (
    dfs["order_items"]
    .groupby("order_id", as_index=False)
    .agg(
        n_items=("order_item_id", "count"),
        n_unique_products=("product_id", "nunique"),
        n_unique_sellers=("seller_id", "nunique"),
        total_price=("price", "sum"),
        total_freight=("freight_value", "sum"),
    )
)

order_items_agg.head()

,order_id,n_items,n_unique_products,n_unique_sellers,total_price,total_freight
0,00010242fe8c5a6d1ba2dd792cb16214,1,1,1,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,1,1,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,1,1,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,1,1,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,1,1,199.90,18.14

In [142]:
payments_agg = (
    dfs["payments"]
    .groupby("order_id", as_index=False)
    .agg(
        n_payments=("payment_sequential", "count"),
        payment_value_total=("payment_value", "sum"),
        payment_installments_max=("payment_installments", "max"),
    )
)

payments_agg.head()

,order_id,n_payments,payment_value_total,payment_installments_max
0,00010242fe8c5a6d1ba2dd792cb16214,1,72.19,2
1,00018f77f2f0320c557190d7a144bdd3,1,259.83,3
2,000229ec398224ef6ca0657da4fc703e,1,216.87,5
3,00024acbcdf0a6daa1e931b038114c75,1,25.78,2
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,218.04,3

In [143]:
customers_selected = dfs["customers"][
    ["customer_id", "customer_unique_id", "customer_city", "customer_state"]
].copy()

customers_selected.head()

,customer_id,customer_unique_id,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,campinas,SP

In [144]:
reviews_agg = (
    dfs["reviews"]
    .groupby("order_id", as_index=False)
    .agg(
        review_score_mean=("review_score", "mean"),
        review_count=("review_id", "count"),
    )
)

reviews_agg.head()

                           order_id  review_score_mean  review_count
0  00010242fe8c5a6d1ba2dd792cb16214                5.0             1
1  00018f77f2f0320c557190d7a144bdd3                4.0             1
2  000229ec398224ef6ca0657da4fc703e                5.0             1
3  00024acbcdf0a6daa1e931b038114c75                4.0             1
4  00042b26cf59d7ce69dfabb4e55b4fd9                5.0             1

In [145]:
sales_analytics = (
    orders_clean
    .merge(order_items_agg, on="order_id", how="left")
    .merge(payments_agg, on="order_id", how="left")
    .merge(customers_selected, on="customer_id", how="left")
    .merge(reviews_agg, on="order_id", how="left")
)

sales_analytics.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,purchase_year,purchase_month,...,total_price,total_freight,n_payments,payment_value_total,payment_installments_max,customer_unique_id,customer_city,customer_state,review_score_mean,review_count
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,2017,10,...,29.99,8.72,3.0,38.71,1.0,7c396fd4830fd04220f754e42b4e5bff,sao paulo,SP,4.0,1.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,2018,7,...,118.70,22.76,1.0,141.46,1.0,af07308b275d755c9edb36a90c618231,barreiras,BA,4.0,1.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,2018,8,...,159.90,19.22,1.0,179.12,3.0,3a653a41f6f9fc3d2a113cf8398680e8,vianopolis,GO,5.0,1.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,2017,11,...,45.00,27.20,1.0,72.20,1.0,7c142cf63193a1473d2e66489a9ae977,sao goncalo do amarante,RN,5.0,1.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2018,2,...,19.90,8.72,1.0,28.62,1.0,72632f0f9dd73dfee390c9b22eb56dd6,santo andre,SP,5.0,1.0

In [146]:
print("sales_analytics shape:", sales_analytics.shape)
print("Unique order_id:", sales_analytics["order_id"].is_unique)
sales_analytics.isna().sum().sort_values(ascending=False).head(15)

sales_analytics shape: (99441, 26)
Unique order_id: True

order_delivered_customer_date    2965
order_delivered_carrier_date     1783
n_unique_products                 775
n_unique_sellers                  775
total_price                       775
total_freight                     775
n_items                           775
review_score_mean                 768
review_count                      768
order_approved_at                 160
payment_installments_max            1
payment_value_total                 1
n_payments                          1
order_estimated_delivery_date       0
order_purchase_timestamp            0
dtype: int64

In [147]:
sales_analytics["delivery_delay_days"] = (
    sales_analytics["order_delivered_customer_date"] - sales_analytics["order_purchase_timestamp"]
).dt.days

sales_analytics["estimated_vs_actual_diff_days"] = (
    sales_analytics["order_delivered_customer_date"] - sales_analytics["order_estimated_delivery_date"]
).dt.days

sales_analytics["total_order_value"] = (
    sales_analytics["total_price"] + sales_analytics["total_freight"]
)

sales_analytics[
    [
        "order_id",
        "total_price",
        "total_freight",
        "total_order_value",
        "delivery_delay_days",
        "estimated_vs_actual_diff_days",
    ]
].head()

,order_id,total_price,total_freight,total_order_value,delivery_delay_days,estimated_vs_actual_diff_days
0,e481f51cbdc54678b7cc49136f2d6af7,29.99,8.72,38.71,8.0,-8.0
1,53cdb2fc8bc7dce0b6741e2150273451,118.70,22.76,141.46,13.0,-6.0
2,47770eb9100c2d0c44946d9cf07ec65d,159.90,19.22,179.12,9.0,-18.0
3,949d5b44dbf5de918fe9c16f97b45f8a,45.00,27.20,72.20,13.0,-13.0
4,ad21c59c0840e6cb83a9ceb5573f8159,19.90,8.72,28.62,2.0,-10.0

In [148]:
delivered_sales = sales_analytics[sales_analytics["order_status"] == "delivered"].copy()

print("delivered_sales shape:", delivered_sales.shape)
print("Unique order_id:", delivered_sales["order_id"].is_unique)

delivered_sales shape: (96478, 29)
Unique order_id: True

## Étape 3 - Construction de la table analytique

L’objectif de cette étape était de construire une table analytique au niveau commande afin de disposer d’une base unique pour les analyses business, les requêtes SQL, le dashboard et le futur modèle de machine learning.

Pour cela, la table `orders_clean` a été utilisée comme table centrale, car elle représente les commandes et constitue l’unité d’analyse la plus adaptée au projet. Les tables `order_items`, `payments` et `reviews` ont d’abord été agrégées au niveau `order_id` afin d’éviter toute duplication des lignes lors des jointures. Cette précaution est essentielle car ces tables possèdent une granularité plus fine que la table des commandes.

L’agrégation de `order_items` a permis de calculer le nombre d’articles, le nombre de produits distincts, le nombre de vendeurs distincts, le montant total des produits et le total des frais de port pour chaque commande. L’agrégation de `payments` a permis de résumer le nombre de paiements, le montant total payé et le nombre maximal d’échéances. La table `customers` a été simplifiée pour conserver uniquement les informations utiles sur les clients, tandis que la table `reviews` a été agrégée par commande afin d’obtenir une note moyenne et un nombre d’avis.

L’ensemble de ces informations a ensuite été fusionné dans une table finale appelée `sales_analytics` à l’aide de jointures de type `left`, afin de conserver toutes les commandes, même lorsque certaines informations étaient absentes dans les tables secondaires.

La table obtenue contient une ligne par commande, avec un identifiant `order_id` toujours unique, ce qui confirme que la granularité a été préservée. Enfin, plusieurs variables métier ont été créées, notamment la valeur totale de la commande, le délai de livraison et l’écart entre la date de livraison réelle et la date estimée. Cette table analytique constitue désormais la base de travail principale pour les analyses business et la modélisation.